In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import LabelEncoder, StandardScaler , MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor 
import matplotlib.pyplot as plt
import seaborn as sns
# import tensorflow as tf
# from sklearn import preprocessing
# import keras 
# # from sklearn.preprocessing import MinMaxScaler
# from sklearn.model_selection import train_test_split
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense , Dropout 
# from tensorflow.keras.callbacks import EarlyStopping
# from tensorflow.keras.optimizers import Adam
# from sklearn.metrics import mean_squared_error, r2_score

#### resuable Functions

In [ ]:
def scale_and_train_and_evaluate_model_ML(df , X , y):
    X_train , X_test , y_train , y_test = train_test_split(X,y , random_state=42 , test_size=0.3)
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    models = {
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "SVR":SVR(kernel='rbf'),
    "RandomForestRegressor":RandomForestRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "KNNeighbours":KNeighborsRegressor(n_neighbors=5)
}
    results = []
    # model_objects = {} # for deployment ig

    for name,model in models.items():
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        r2 = r2_score(y_test , y_pred)
        mse = mean_squared_error(y_test , y_pred)
        mae = mean_absolute_error(y_test , y_pred)
        results.append({
            "Model":name,
            "MAE":mae,
            "R2-Value":r2,
            "MSE":mse
        })
        # print(model)
        # print(model_objects[name])
        # print(model_objects)
        results_df = pd.DataFrame(results).sort_values(
        by="R2-Value", ascending=False
    )
    
    return results_df

In [4]:
df = pd.read_csv('model_training.csv')
df.sample(10)

,coverage_risk,demo_volatility,bio_compliance_risk,ALRI,ALRI_next_month
15223,0.500000,0.000000,0.800000,0.390000,1.458301
19254,0.029412,0.000000,0.727273,0.227005,191.094680
31852,0.062500,0.039447,0.653846,7.744401,1.588022
20185,0.125000,0.771909,0.660377,147.575402,5.725136
50274,0.200000,0.003201,0.800000,0.911010,1.306645
23738,0.500000,0.395639,0.750000,75.893475,0.250000
27398,0.500000,0.001210,0.250000,0.455940,57.956557
63558,0.333333,0.003630,0.750000,1.017820,1.207666
57090,0.222222,0.000000,0.161616,0.115152,1.967745
17414,0.333333,0.000000,0.714286,0.314286,0.234211

In [5]:
df.shape

(74364, 5)

### Target Feature : ALRI
ALRI = weighted combination of multiple risk signals
| Risk                      | What it captures                 |
| ------------------------- | -------------------------------- |
| Coverage_Risk             | People missing Aadhaar           |
| Data_Instability_Risk     | Aadhaar data becoming unreliable |
| Biometric_Compliance_Risk | Future authentication failures   |

In [ ]:
X = df[
    ['coverage_risk', 'demo_volatility', 'bio_compliance_risk', 'ALRI']
]
y = df['ALRI_next_month']

In [10]:
# df = df.shift(-1)
X,y

(       coverage_risk  demo_volatility  bio_compliance_risk        ALRI
 0           0.115385         1.000000             0.529412  191.070472
 1           0.021978         1.000000             0.669484  191.084471
 2           0.034296         1.000000             0.320450  190.983456
 3           0.113402         1.000000             0.498050  191.060468
 4           0.038869         1.000000             0.673626  191.090781
 ...              ...              ...                  ...         ...
 74359       0.034483         0.001210             0.500000    0.391285
 74360       0.034483         0.001210             0.500000    0.391285
 74361       0.034483         0.001210             0.500000    0.391285
 74362       0.500000         0.007259             0.666667    1.735641
 74363       0.100000         0.065334             1.000000   12.800766

 [74364 rows x 4 columns],
 0          0.428571
 1        191.071603
 2        191.008388
 3        191.040348
 4        191.091015
             ...
 74359      0.391285
 74360      0.391285
 74361      0.391285
 74362      1.835641
 74363     12.628901
 Name: ALRI_next_month, Length: 74364, dtype: float64)

In [8]:
df.sample(10)

,coverage_risk,demo_volatility,bio_compliance_risk,ALRI,ALRI_next_month
14217,0.500000,0.000000,0.333333,0.250000,1.182666
50603,0.111111,0.000000,0.583333,0.208333,3.467811
47614,0.090909,0.653394,0.481481,124.889639,1.020093
25974,0.250000,0.003201,0.800000,0.926010,1.642221
22147,0.500000,1.000000,0.750000,191.252033,0.265873
54123,0.083333,0.030102,0.692308,5.978415,0.204545
46779,0.100000,0.000000,0.611111,0.213333,74.252077
6061,0.333333,0.000000,0.833333,0.350000,0.275000
67835,0.250000,0.047464,0.833333,9.384801,9.773265
13330,0.055556,0.030223,0.234848,5.856003,0.080174

In [11]:
scale_and_train_and_evaluate_model_ML(df, X,y)

                   Model        MAE  R2-Value          MSE
1                  Ridge  17.164363  0.071673  1299.492312
0       LinearRegression  17.164357  0.071673  1299.492431
2                  Lasso  17.245507  0.071494  1299.742959
4  RandomForestRegressor  17.317957 -0.035130  1448.997122
3                    SVR  11.488240 -0.049708  1469.403413
6           KNNeighbours  17.625410 -0.061103  1485.354974
5  DecisionTreeRegressor  18.787939 -0.637488  2292.190247

In [13]:
from scipy.stats import spearmanr
spearman_corr, _ = spearmanr(
    df['ALRI_next_month'],
    df['ALRI']
)

spearman_corr

np.float64(0.2267253563072099)